Drug labels in pml
tom-and-the-toothfairies/pathways pull request #107
Opened 2017-03-08 19:36 UTC by c-brenn

new drug format as per customer's requests.

2017-03-08 19:40 UTC, c-brenn commented
drugs can be specified in PML like so
```
requires { drug { "paracetamol" } }
```

* `/api/pml` returns the list of english drugs in a pml file
* `/api/uris` takes a list of english drugs and uses the new asclpius endpoints to find their uris
* `api/ddis` takes a list of uris and returns their ddis

The front-end code works but is nice and ugly. The `content-type` has to be explicitly set to `application/json` or else phoenix thinks it's `text/plain`

2017-03-08 19:45 UTC, c-brenn commented on panacea/web/static/js/app.js
> +        console.log(uris);
will remove this

2017-03-08 20:13 UTC, houli requested changes

2017-03-08 20:13 UTC, houli commented on asclepius/README.md
> +{"labels": [ "paracetamol", "flat seven up", "cocaine"]}
Does this need to be labels or can we just send the list with no object around it?

2017-03-08 20:13 UTC, houli commented on asclepius/README.md
> +  "drugs": [
Does this need to be drugs or can we just send the list with no object around it? Realise this is an old one but sure

2017-03-08 20:13 UTC, houli commented on asclepius/README.md
> +  "found": {
Maybe we want this instead
```json
{
  "found": [
    {
      "uri": "http://purl.obolibrary.org/obo/CHEBI_27958",
      "label": "cocaine"
    },
    {
      "uri": "http://purl.obolibrary.org/obo/CHEBI_46195",
      "label": "paracetamol"
    }
  ],
  "not_found": [
    "flat seven up"
  ]
}
```

2017-03-08 20:13 UTC, houli commented on asclepius/asclepius/dinto.py
> +        if not isinstance(labels, frozenset):
Not sure we need to catch this, we should accept any hashable, if it's not hashable then the lru_cache will throw anyway

2017-03-08 20:13 UTC, houli commented on asclepius/asclepius/dinto.py
> +    print(drugs)
Presume this isn't needed

2017-03-08 20:13 UTC, houli commented on panacea/web/static/js/app.js
> +    const drugs_response = await fetch(this.action, {
A style thing for the JS bits camelCase it

2017-03-08 20:13 UTC, houli commented on panacea/web/static/js/app.js
>        headers: new Headers({authorization: apiAccessToken})
We'll probably want `'Accept': 'application/json, text/plain, */*'` headers on all of these requests

2017-03-08 20:24 UTC, c-brenn commented on asclepius/README.md
> +  "found": {
our reasoning for the current format is that when DDIs are returned the front-end will need to lookup the names of the drugs in each DDI. The DDIs return URIs for the participating drugs. The map format makes this easy.

2017-03-08 20:29 UTC, c-brenn commented on asclepius/README.md
> +  "drugs": [
Perhaps not needed - I kind of like the context that the outer object gives though.

2017-03-08 20:36 UTC, 22a commented
Working on the live updates(drugs show up before ddis are queried), pls don't merge yet 💇‍♂️

2017-03-08 21:00 UTC, c-brenn commented on asclepius/asclepius/main.py
> +        raise InvalidUsage("Expecting {'labels': [...]} with at least two labels")
this message doesn't really match up

2017-03-08 21:47 UTC, c-brenn commented on panacea/web/static/js/app.js
> +          const unidentifiedDrugs = Object.values(data.uris.not_found);
not sure if you need Object.values here.  I think not_found is just a list.

2017-03-08 21:49 UTC, 22a commented on panacea/web/static/js/app.js
> +          const unidentifiedDrugs = Object.values(data.uris.not_found);
oops lol

2017-03-08 21:51 UTC, 22a commented
few things going on in that last commit:
* added unidentified drugs panel
* added sample pml file with silly "drugs" for manual visual testing of panels
* removed superfluous class removal in the display functions (the classes get reset at the start of the request chain)

the unidentified panel looks like this:
<img width="1393" alt="screen shot 2017-03-08 at 21 37 27" src="https://cloud.githubusercontent.com/assets/7144173/23725639/45bcc6f6-0449-11e7-84fb-dd930d659637.png">


it also raises a few questions:
* what do we want to display to the user when the request chain is broken at the different points (when found URI's is less than `2` and when identifiable drugs is less than `0`{thinking about this, this should also probably be `2`, as there's no point getting the uri of one drug alone) 
* do we want to make the error panel more expressive (where we can change the panel header as well)

2017-03-08 21:53 UTC, 22a commented
also, the request chain is getting quite hairy now(v nested), perhaps we could consider breaking the chain out to separate handlers? **bleugh**

2017-03-08 21:55 UTC, c-brenn commented
Nice work.

👍 yeah I'm all for refactoring the request chain.

I think we need a bigger discussion about the UI that's beyond the scope of this PR.

2017-03-08 22:02 UTC, 22a commented on panacea/web/static/js/app.js
> +        displayError({"message": "No drugs found"});
this is old syntax, `{message: "bleugh"}` would be nicer, i see we have used it above

2017-03-09 08:23 UTC, c-brenn commented
think this is ready to go - any further changes needed?

2017-03-09 10:31 UTC, 22a commented
Looks good to 🚢  the 🐶 to me. @houli will need to approve his requested changes as I feel dismissing his review would be a breach of interpersonal trust and set a worrying precedent

2017-03-09 10:38 UTC, c-brenn commented
Actually, the frontend changes should go in he change log.

* the unidentified drugs
* change in spinner behaviour

2017-03-09 10:39 UTC, 22a commented
Good spot, will add those now

2017-03-09 14:59 UTC, houli approved these changes

2017-03-09 15:03 UTC, merged