Ast endpoints
tom-and-the-toothfairies/pathways pull request #146
Opened 2017-03-17 18:47 UTC by c-brenn

* `/api/pml` returns the AST as part of the repsonse - see readme

* `/api/ast` takes an AST and returns the corresponding PML as an attachment

2017-03-17 21:19 UTC, 22a commented
added a pml download button

it looks and works like this:
![2017-03-17 21_13_10](https://cloud.githubusercontent.com/assets/7144173/24063398/5f4385e6-0b57-11e7-91a2-129dbd5f33c7.gif)

2017-03-17 21:26 UTC, 22a commented
The time at which we call [these](https://github.com/tom-and-the-toothfairies/pathways/pull/146/files#diff-af326ae966b05ea64b817eac7636661eR83) is up for debate, the functions were designed in such a way so as to facilitate multiple ast revisions (necessary if PML-TX features are purchased)

2017-03-18 16:12 UTC, houli requested changes

2017-03-18 16:12 UTC, houli commented on panacea/web/static/js/app.js
> +};
Instead of this stuff we can use `Blob` api I believe

2017-03-18 16:12 UTC, houli commented on panacea/web/static/js/app.js
> +  pmlDownloadButton.onclick = async function(){
addEventListener

2017-03-18 16:12 UTC, houli commented on panacea/web/static/css/app.css
> +.padded-bottom {
Instead of this padded class will using bootstrap `row` bits get us the right padding we want?

2017-03-19 15:07 UTC, houli commented on panacea/web/static/js/request.js
> +export const apiAccessToken = document.getElementById('api-access-token').content;
Don't need an export any more if I'm not mistaken

2017-03-19 18:28 UTC, houli approved these changes

2017-03-19 19:59 UTC, merged